.TH "src/tone_helper.h" 3 "esp32c3_lib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tone_helper.h
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <driver/ledc\&.h>\fP
.br

.SS "マクロ定義"

.in +1c
.ti -1c
.RI "#define \fBBUZZER_PIN\fP   4"
.br
.ti -1c
.RI "#define \fBBZ_CHANNEL\fP   LEDC_CHANNEL_0"
.br
.ti -1c
.RI "#define \fBBZ_TIMER\fP   LEDC_TIMER_0"
.br
.ti -1c
.RI "#define \fBBZ_MODE\fP   LEDC_LOW_SPEED_MODE"
.br
.ti -1c
.RI "#define \fBBZ_RES\fP   LEDC_TIMER_8_BIT"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "void \fBtoneESP\fP (uint32_t freq, uint32_t duration_ms)"
.br
.RI "指定された周波数と期間でトーンを生成します。 "
.ti -1c
.RI "void \fBbeepOK\fP ()"
.br
.RI "成功を示す短いビープ音を鳴らします。 "
.ti -1c
.RI "void \fBbeepError\fP ()"
.br
.RI "エラーを示すビープ音を鳴らします。 "
.in -1c
.SH "マクロ定義詳解"
.PP 
.SS "#define BUZZER_PIN   4"

.SS "#define BZ_CHANNEL   LEDC_CHANNEL_0"

.SS "#define BZ_MODE   LEDC_LOW_SPEED_MODE"

.SS "#define BZ_RES   LEDC_TIMER_8_BIT"

.SS "#define BZ_TIMER   LEDC_TIMER_0"

.SH "関数詳解"
.PP 
.SS "void beepError ()\fC [inline]\fP"

.PP
エラーを示すビープ音を鳴らします。 
.SS "void beepOK ()\fC [inline]\fP"

.PP
成功を示す短いビープ音を鳴らします。 
.SS "void toneESP (uint32_t freq, uint32_t duration_ms)"

.PP
指定された周波数と期間でトーンを生成します。 LEDCタイマーとチャンネルを設定し、指定された周波数でデューティサイクル50のPWM信号を出力します。 
.PP
\fB引数\fP
.RS 4
\fIfreq\fP トーンの周波数（Hz）。 
.br
\fIduration_ms\fP トーンを鳴らす期間（ミリ秒）。 
.RE
.PP

.SH "著者"
.PP 
 esp32c3_libのソースコードから抽出しました。
